### ISSUE TITLE
Error installing through MSYS2

### ISSUE THREAD

**Issue by MarioPossamato** [pyimgui/pyimgui#262]
I'm trying to install pyimgui through MSYS2 on Windows 11.  Not sure if this is an issue with my environment, or with pyimgui itself, but whenever I run ```pip3 install imgui[full]``` in MSYS2, I receive this output:
```
$ pip3 install imgui[full]
Collecting imgui[full]
  Downloading imgui-1.4.1.tar.gz (855 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 855.1/855.1 KB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyOpenGL
  Using cached PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
Collecting Cython<0.30,>=0.24
  Using cached Cython-0.29.28-py2.py3-none-any.whl (983 kB)
Collecting PySDL2
  Downloading PySDL2-0.9.11-py3-none-any.whl (538 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 538.5/538.5 KB 6.9 MB/s eta 0:00:00
Collecting pygame
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 7.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using UNIX configuration...

      /bin/sh: line 1: sdl2-config: command not found
      /bin/sh: line 1: sdl2-config: command not found
      /bin/sh: line 1: sdl2-config: command not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bvbbaflp/pygame_b1ceef14e6294e958e1eb95ac37c4a55/setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "/tmp/pip-install-bvbbaflp/pygame_b1ceef14e6294e958e1eb95ac37c4a55/buildconfig/config.py", line 225, in main
          deps = CFG.main(**kwds)
        File "/tmp/pip-install-bvbbaflp/pygame_b1ceef14e6294e958e1eb95ac37c4a55/buildconfig/config_unix.py", line 188, in main
          DependencyProg('SDL', 'SDL_CONFIG', 'sdl2-config', '2.0', ['sdl']),
        File "/tmp/pip-install-bvbbaflp/pygame_b1ceef14e6294e958e1eb95ac37c4a55/buildconfig/config_unix.py", line 39, in __init__
          self.ver = config[0].strip()
      IndexError: list index out of range

      Hunting dependencies...

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/Compilation
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
Python version is 3.9.7.  I'm almost certain this is a result of something I did wrong, or something I have set up incorrectly, but I may be wrong.  I've tried different things, none of which worked.  Any advice?

My apologies if this is an inane question! 😅

Also, please let me know if more information is required.

Thanks!

**Comment by learn-more** [comment]
To track down if this is a problem with your machine or there is a bug at work here, can you please try to create a new clean virtual python environment (with venv: https://docs.python.org/3/library/venv.html)

for your reference, this is how this would look like on my win10 machine (without msys2):


```
C:\Users\Mark.DEV2>cd %tmp%

C:\Users\MARK~1.DEV\AppData\Local\Temp>mkdir test_env

C:\Users\MARK~1.DEV\AppData\Local\Temp>py -m venv test_env

C:\Users\MARK~1.DEV\AppData\Local\Temp>test_env\Scripts\activate.bat

(test_env) C:\Users\MARK~1.DEV\AppData\Local\Temp>pip install imgui[full]
Collecting imgui[full]
  Using cached imgui-1.4.1-cp39-cp39-win_amd64.whl (1.1 MB)
Collecting pygame
  Downloading pygame-2.1.2-cp39-cp39-win_amd64.whl (8.4 MB)
     |████████████████████████████████| 8.4 MB 3.3 MB/s
Collecting cocos2d
  Downloading cocos2d-0.6.9.tar.gz (4.7 MB)
     |████████████████████████████████| 4.7 MB 2.2 MB/s
Collecting glfw
  Using cached glfw-2.5.0-py2.py27.py3.py30.py31.py32.py33.py34.py35.py36.py37.py38-none-win_amd64.whl (491 kB)
Collecting pyglet
  Using cached pyglet-1.5.21-py3-none-any.whl (1.1 MB)
Collecting Cython<0.30,>=0.24
  Downloading Cython-0.29.28-py2.py3-none-any.whl (983 kB)
     |████████████████████████████████| 983 kB 2.2 MB/s
Collecting PyOpenGL
  Using cached PyOpenGL-3.1.5-py3-none-any.whl (2.4 MB)
Collecting PySDL2
  Downloading PySDL2-0.9.11-py3-none-any.whl (538 kB)
     |████████████████████████████████| 538 kB 6.8 MB/s
Collecting six>=1.4
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Using legacy 'setup.py install' for cocos2d, since package 'wheel' is not installed.
Installing collected packages: six, pyglet, PySDL2, PyOpenGL, pygame, imgui, glfw, Cython, cocos2d
    Running setup.py install for cocos2d ... done
Successfully installed Cython-0.29.28 PyOpenGL-3.1.5 PySDL2-0.9.11 cocos2d-0.6.9 glfw-2.5.0 imgui-1.4.1 pygame-2.1.2 pyglet-1.5.21 six-1.16.0
WARNING: You are using pip version 21.1.3; however, version 22.0.3 is available.
You should consider upgrading via the 'c:\users\mark~1.dev\appdata\local\temp\test_env\scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by MarioPossamato** [comment]
I am now receiving this output:
```
Collecting imgui[full]
  Downloading imgui-1.4.1.tar.gz (855 kB)
     ---------------------------------------- 855.1/855.1 KB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cocos2d
  Downloading cocos2d-0.6.9.tar.gz (4.7 MB)
     ---------------------------------------- 4.7/4.7 MB 6.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pygame
  Downloading pygame-2.1.2.tar.gz (10.1 MB)
     ---------------------------------------- 10.1/10.1 MB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [70 lines of output]


      WARNING, No "Setup" File Exists, Running "buildconfig/config.py"
      Using WINDOWS configuration...

      Traceback (most recent call last):
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 1346, in do_open
          h.request(req.get_method(), req.selector, req.data, headers,
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 1285, in request
          self._send_request(method, url, body, headers, encode_chunked)
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 1331, in _send_request
          self.endheaders(body, encode_chunked=encode_chunked)
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 1280, in endheaders
          self._send_output(message_body, encode_chunked=encode_chunked)
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 1040, in _send_output
          self.send(msg)
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 980, in send
          self.connect()
        File "C:\msys64\mingw64\lib\python3.9\http\client.py", line 1454, in connect
          self.sock = self._context.wrap_socket(self.sock,
        File "C:\msys64\mingw64\lib\python3.9\ssl.py", line 500, in wrap_socket
          return self.sslsocket_class._create(
        File "C:\msys64\mingw64\lib\python3.9\ssl.py", line 1040, in _create
          self.do_handshake()
        File "C:\msys64\mingw64\lib\python3.9\ssl.py", line 1309, in do_handshake
          self._sslobj.do_handshake()
      ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\setup.py", line 359, in <module>
          buildconfig.config.main(AUTO_CONFIG)
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\config.py", line 225, in main
          deps = CFG.main(**kwds)
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\config_win.py", line 497, in main
          and download_win_prebuilt.ask(**download_kwargs):
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\download_win_prebuilt.py", line 290, in ask
          update(x86=x86, x64=x64)
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\download_win_prebuilt.py", line 273, in update
          download_prebuilts(download_dir, x86=x86, x64=x64)
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\download_win_prebuilt.py", line 124, in download_prebuilts
          download_sha1_unzip(url, checksum, temp_dir, 1)
        File "C:\Users\User1\AppData\Local\Temp\pip-install-e2_wfe3i\pygame_df50a2b0ab6946d08aac222242402ff0\buildconfig\download_win_prebuilt.py", line 54, in download_sha1_unzip
          response = urllib.urlopen(request).read()
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 214, in urlopen
          return opener.open(url, data, timeout)
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 517, in open
          response = self._open(req, data)
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 534, in _open
          result = self._call_chain(self.handle_open, protocol, protocol +
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 494, in _call_chain
          result = func(*args)
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 1389, in https_open
          return self.do_open(http.client.HTTPSConnection, req,
        File "C:\msys64\mingw64\lib\python3.9\urllib\request.py", line 1349, in do_open
          raise URLError(err)
      urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>
      Making dir :prebuilt_downloads:
      Downloading... https://www.libsdl.org/release/SDL2-devel-2.0.18-VC.zip ed561079ec622b0bab5a9e02976f5d540b0622da

      ---
      For help with compilation see:
          https://www.pygame.org/wiki/CompileWindows
      To contribute to pygame development see:
          https://www.pygame.org/contribute.html
      ---

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by learn-more** [comment]
the pygame does indeed seem to have a problem installing under msys2,
so I'd recommend to either install only the components that you need, or ditch msys2 and run it directly on Windows itself.
