### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by Cold-Studio** [pyimgui/pyimgui#281]
Using Linux 
Lubuntu

Code:
```
import imgui
imgui.create_context()
imgui.get_io().display_size = 100, 100

# Create Window
imgui.new_frame()
imgui.begin("Window Name", True)
imgui.text("My first Text")
imgui.end()
imgui.render()
imgui.end_frame()
```
Pip's:
```
aiogram==2.20
aiohttp==3.8.1
aiosignal==1.2.0
apt-xapian-index==0.49
async-timeout==4.0.2
attrs==21.4.0
Babel==2.9.1
blinker==1.4
certifi==2021.10.8
chardet==4.0.0
charset-normalizer==2.0.12
click==8.0.3
colorama==0.4.4
command-not-found==0.3
cryptography==3.4.8
cupshelpers==1.0
Cython==0.29.28
dbus-python==1.2.18
dearpygui==1.6.1
defer==1.0.6
distro==1.7.0
distro-info===1.1build1
docutils==0.18.1
frozenlist==1.3.0
galternatives==1.0.8
glcontext==2.3.6
glfw==2.5.3
greenlet==1.1.2
gyp==0.1
httplib2==0.20.2
idna==3.3
imgui==1.4.1
importlib-metadata==4.6.4
jeepney==0.7.1
keyring==23.5.0
Kivy==2.1.0
Kivy-Garden==0.1.5
language-selector==0.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
llvmlite==0.38.0
lubuntu-update-notifier==0.4.dev0
moderngl==5.6.4
more-itertools==8.10.0
msgpack==1.0.3
multidict==6.0.2
neovim==0.3.1
netifaces==0.11.0
numba==0.55.1
numpy==1.21.6
oauthlib==3.2.0
objloader==0.2.0
olefile==0.46
opencv-python==4.5.5.64
pexpect==4.8.0
Pillow==9.0.1
ptyprocess==0.7.0
pycairo==1.20.1
pycups==2.0.1
pyglet==1.5.23
Pygments==2.12.0
PyGObject==3.42.0
PyJWT==2.3.0
pynvim==0.4.2
PyOpenGL==3.1.6
pyparsing==2.4.7
PyQt5==5.15.6
PyQt5-sip==12.9.1
python-apt==2.3.0+ubuntu2
python-debian===0.1.43ubuntu1
pytz==2022.1
pyxdg==0.27
PyYAML==5.4.1
reportlab==3.6.8
requests==2.27.1
SecretStorage==3.3.1
six==1.16.0
systemd-python==234
tk==0.1.0
ubuntu-advantage-tools==27.8
ubuntu-drivers-common==0.0.0
ufw==0.36.1
unattended-upgrades==0.1
urllib3==1.26.9
usb-creator==0.3.7
wadllib==1.3.6
xdg==5
xkit==0.0.0
yarl==1.7.2
zipp==1.0.0
```

Error:
```
bankalore@bankaipc:~/Documents/PyGUI$ python imgui.py
Traceback (most recent call last):
  File "/home/bankalore/Documents/PyGUI/imgui.py", line 1, in <module>
    import imgui
  File "/home/bankalore/Documents/PyGUI/imgui.py", line 2, in <module>
    imgui.create_context()
AttributeError: partially initialized module 'imgui' has no attribute 'create_context' (most likely due to a circular import)
```

And i using this project
```
pacanada/boids-simulation
https://github.com/pacanada/boids-simulation
```
Full work, please help

**Comment by KinoxKlark** [comment]
What branch do you use? Do examples work?
