### ISSUE TITLE
Crash when you have a combo and a input_text in the same widget

### ISSUE THREAD

**Issue by tayler6000** [pyimgui/pyimgui#310]
Hello, I am using python 3.10.7, pygame 2.1.2, and pyimgui 2.0 installed from the dev/version-2.0 branch at commit `4c08933d2c09ad4c94db84418bf25ddfd1db6eba`. (Latest at time of posting)

I am able to have both a combo box and an input_text field in separate widgets, however, once I have them in the same widget the combo box's drop-down no longer works and if you try to use the input_text it crashes with the following error:

```py3
pygame 2.1.2 (SDL 2.0.18, Python 3.10.7)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "test.py", line 73, in <module>
    main()
  File "test.py", line 58, in main
    _, selected = imgui.combo("", selected, things)
  File "imgui\core.pyx", line 6677, in imgui.core.combo
imgui.core.ImGuiError: ImGui assertion error (mouse_button >= 0 && mouse_button < ImGuiMouseButton_COUNT) at imgui-cpp/imgui_widgets.cpp:627
```

I'm using a slightly modified version of the pygame integration example.

```py3
from __future__ import absolute_import

import sys

import pygame
import OpenGL.GL as gl

from imgui.integrations.pygame import PygameRenderer
import imgui


def main():
    pygame.init()
    size = 800, 600

    pygame.display.set_mode(size, pygame.DOUBLEBUF | pygame.OPENGL | pygame.RESIZABLE)

    imgui.create_context()
    impl = PygameRenderer()

    io = imgui.get_io()
    io.display_size = size

    show_custom_window = True
    selected = 0
    text = ""

    while 1:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                sys.exit()
            impl.process_event(event)
        impl.process_inputs()

        imgui.new_frame()

        if imgui.begin_main_menu_bar():
            if imgui.begin_menu("File", True):

                clicked_quit, selected_quit = imgui.menu_item(
                    "Quit", "Cmd+Q", False, True
                )

                if clicked_quit:
                    exit(1)

                imgui.end_menu()
            imgui.end_main_menu_bar()

        imgui.show_test_window()

        things = ["A", "B", "C"]
        if show_custom_window:
            is_expand, show_custom_window = imgui.begin("Custom window", True)
            if is_expand:
                imgui.text("Bar")
                imgui.text_colored("Eggs", 0.2, 1.0, 0.0)
                _, selected = imgui.combo("", selected, things)
                _, text = imgui.input_text("", text, 10)
            imgui.end()

        # note: cannot use screen.fill((1, 1, 1)) because pygame's screen
        #       does not support fill() on OpenGL sufraces
        gl.glClearColor(1, 1, 1, 1)
        gl.glClear(gl.GL_COLOR_BUFFER_BIT)
        imgui.render()
        impl.render(imgui.get_draw_data())

        pygame.display.flip()


if __name__ == "__main__":
    main()
```

Any idea what's causing this issue?

**Comment by tayler6000** [comment]
Apparently, this can happen when for more than these types of inputs, is this just a problem with dear imgui?

**Comment by xstal7** [comment]
[For Your Information]
I had a similar problem and spent some time trying to solve it.
The problem is the same label of different widgets within a window.

**Comment by learn-more** [comment]
> [For Your Information] I had a similar problem and spent some time trying to solve it. The problem is the same label of different widgets within a window.

Indeed.
You are passing both an empty string, but it needs a unique ID.
If you want it to display empty, add a double hashtag in the name, and some unique text after that.
It will not be displayed, but will be used for generating a unique ID.

```
                _, selected = imgui.combo("##things", selected, things)
                _, text = imgui.input_text("##input_text", text, 10)
```
