### ISSUE TITLE
OpenGL.error.Error: Attempt to retrieve context when no valid context (Wayland)

### ISSUE THREAD

**Issue by JosephFerano** [pyimgui/pyimgui#318]
Hi, thank you for this package!

I am having issues when using this library with the GLFW backend. I am trying to run the example code provided [here](https://github.com/pyimgui/pyimgui/blob/master/doc/examples/integrations_glfw3.py). Here is the full error;

```
Traceback (most recent call last):
  File "/home/joe/Development/moon-miner/test.py", line 84, in <module>
    main()
  File "/home/joe/Development/moon-miner/test.py", line 11, in main
    impl = GlfwRenderer(window)
  File "/home/joe/.local/lib/python3.10/site-packages/imgui/integrations/glfw.py", line 13, in __init__    super(GlfwRenderer, self).__init__()
  File "/home/joe/.local/lib/python3.10/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/home/joe/.local/lib/python3.10/site-packages/imgui/integrations/base.py", line 17, in __init__    self._create_device_objects()
  File "/home/joe/.local/lib/python3.10/site-packages/imgui/integrations/opengl.py", line 125, in _create_device_objects
    gl.glVertexAttribPointer(self._attrib_location_position, 2, gl.GL_FLOAT, gl.GL_FALSE, imgui.VERTEX_SIZE, ctypes.c_void_p(imgui.VERTEX_BUFFER_POS_OFFSET))
  File "/home/joe/.local/lib/python3.10/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/joe/.local/lib/python3.10/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 469, in glVertexAttribPointer
    contextdata.setValue( key, array )
  File "/home/joe/.local/lib/python3.10/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
  File "/home/joe/.local/lib/python3.10/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context

```

I tried with both Python 3.10 and 3.11.

I am on Fedora 37 running Gnome 43 on Wayland. If I switch to Gnome on Xorg, the error doesn't occur and I am able to run the sample code as well as the project I'm working on, with both Python 3.10 and 3.11

**Comment by JosephFerano** [comment]
Small update, I tried out Pyglet and Pygame backends and I see the same error.  When attempting to use the SDL2 backend, I see this error;

`Error: Cannot create OpenGL Context! SDL Error: Invalid window`

Finally, I forgot to mention, but I'm using version 2.0.0 of pyimgui that I manually installed from `dev/version-2.0`

My suspicion is that there's something at play here, perhaps a flag or a setting I need to set in order to get it working with Wayland correctly. Any help would be appreciated.

**Comment by chrishavlin** [comment]
I just started seeing this error in an application using the pyimgui-pyglet backend after upgrading to Ubuntu 22.04.2 (which now uses Wayland by default). I actually found that pinning PyOpenGL==3.1.5 fixes the error though I don't know why... 

@JosephFerano did you ever figure out if there was a flag that was helpful?

**Comment by JosephFerano** [comment]
> @JosephFerano did you ever figure out if there was a flag that was helpful?

@chrishavlin Nope, it's working with the SDL2 backend on Wayland for me at the moment. I have no idea what I did to fix it. Perhaps an update to my distro (Fedora) fixed it? I haven't touched this in months.

**Comment by chrishavlin** [comment]
After more fiddling this morning, I found that setting the  `PYOPENGL_PLATFORM` to `glx` (on Ubuntu, `export PYOPENGL_PLATFORM='glx'`) actually fixes the error. So something is going wrong in the automated platform selection. I know pyglet does not support Wayland at present, so maybe PyOpenGL is selecting an incompatible session type, but only when I'm using pyimgui (all the pyglet examples I've tested run just fine on their own). At this point I'm well out of my depth, but if anyone has any suggestions on where to look I'm happy to keep digging.

**Comment by Johndeep** [comment]
Also as a still-Ubuntu-22.04 user (still pending if  24.04 or directly Debian due to massive snap ads and Ubuntu Pro stuff I really don't need), in my case, this works:
`PYOPENGL_PLATFORM='egl' python3 -m <the app>`

Or, if you use either VSCode or VSCodium, add the "env" configuration to the launch.js file, so you don't need to call it every time you want to launch it:
```json
"configurations": [
    {
        "env": {
            "PYOPENGL_PLATFORM": "egl"
        }
    }
```

The `glx` variant doesn't work for me. Both are still workarounds, I guess. Also because in case of GLFW, there are no native window decorations. If anyone is more knowledgeable and want to find more hints for solving this, you might want to take a look at the imgui-bundle project, since it can run directlyy on Wayland just fine. With proper window decorations.

**Comment by Echo-jyt** [comment]
> #### About the **glfw integration**,
> as a still-Ubuntu-22.04 user (still pending if 24.04 or directly Debian due to massive snap ads and Ubuntu Pro stuff I really don't need), this works for me: `PYOPENGL_PLATFORM='egl' python3 -m <the app>`
> 
> Or, if you use either VSCode or VSCodium, add the "env" configuration to the launch.js file, so you don't need to call it every time you want to launch it:
> 
> ```json
> "configurations": [
>     {
>         "env": {
>             "PYOPENGL_PLATFORM": "egl"
>         }
>     }
> ```
> 
> The variant doesn't work for me. Both are still workarounds, I guess. Also because with **glfw**, there are no native window decorations. If anyone is more knowledgeable and want to find more hints for solving this, you might want to take a look at the [**imgui-bundle**](https://github.com/pthom/imgui_bundle) project, since it can run **sdl2** and **glfw** directly on Wayland just fine. With proper window decorations.`glx`
> 
> #### About the **sdl2 integration**,
> this works fine on Ubuntu 22.04 with Wayland in my case. Or at least the example code provided in the docs. Without env and with native window decoration.
> 
> I might add, that I tried both the _main_ and the _docking_ branch, since the docking branch seems to be ahead quite some commits. But still no proper fix for glfw with wayland it seems (as of now).



> #### About the **glfw integration**,
> as a still-Ubuntu-22.04 user (still pending if 24.04 or directly Debian due to massive snap ads and Ubuntu Pro stuff I really don't need), this works for me: `PYOPENGL_PLATFORM='egl' python3 -m <the app>`
> 
> Or, if you use either VSCode or VSCodium, add the "env" configuration to the launch.js file, so you don't need to call it every time you want to launch it:
> 
> ```json
> "configurations": [
>     {
>         "env": {
>             "PYOPENGL_PLATFORM": "egl"
>         }
>     }
> ```
> 
> The variant doesn't work for me. Both are still workarounds, I guess. Also because with **glfw**, there are no native window decorations. If anyone is more knowledgeable and want to find more hints for solving this, you might want to take a look at the [**imgui-bundle**](https://github.com/pthom/imgui_bundle) project, since it can run **sdl2** and **glfw** directly on Wayland just fine. With proper window decorations.`glx`
> 
> #### About the **sdl2 integration**,
> this works fine on Ubuntu 22.04 with Wayland in my case. Or at least the example code provided in the docs. Without env and with native window decoration.
> 
> I might add, that I tried both the _main_ and the _docking_ branch, since the docking branch seems to be ahead quite some commits. But still no proper fix for glfw with wayland it seems (as of now).

thank you very much!  add the "env" configuration to the launch.js file is useful for me!

**Comment by ChenglongLee** [comment]
OpenGL.error.Error: Attempt to retrieve context when no valid context
