### ISSUE TITLE
imgui with Opengl 3.3 yields OpenGL.error.GLError about glTexImage2D

### ISSUE THREAD

**Issue by cgloeckner** [pyimgui/pyimgui#329]
Hey there,

I try to use imgui (via pygame and moderngl) using opengl 3.3, but I struggle with an `OpenGL.error.GLError`. Here's my code:

```python
import pygame
import imgui
import moderngl
from imgui.integrations.pygame import PygameRenderer

pygame.init()
pygame.display.gl_set_attribute(pygame.GL_CONTEXT_MAJOR_VERSION, 3)
pygame.display.gl_set_attribute(pygame.GL_CONTEXT_MINOR_VERSION, 3)
pygame.display.gl_set_attribute(pygame.GL_CONTEXT_PROFILE_MASK, pygame.GL_CONTEXT_PROFILE_CORE)

pygame.display.set_mode((800, 600), flags=pygame.OPENGL | pygame.DOUBLEBUF)
context = moderngl.create_context()

imgui.create_context()
impl = PygameRenderer()
io = imgui.get_io()
io.display_size = (800, 600)

while True:
	for event in pygame.event.get():
		impl.process_event(event)

	imgui.new_frame()
	imgui.show_test_window()
	
	context.clear()
	imgui.render()
	impl.render(imgui.get_draw_data())
	pygame.display.flip()
```

If I don't specify the version to be 3.3, it'll stick to 2.1 and imgui works. But with 3.3 I'm getting this traceback:
```python
pygame 2.0.1 (SDL 2.0.14, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "pygame_moderngl_imgui.py", line 15, in <module>
    impl = PygameRenderer()
  File "/home/glocke/.local/lib/python3.8/site-packages/imgui/integrations/pygame.py", line 14, in __init__
    super(PygameRenderer, self).__init__()
  File "/home/glocke/.local/lib/python3.8/site-packages/imgui/integrations/base.py", line 18, in __init__
    self.refresh_font_texture()
  File "/home/glocke/.local/lib/python3.8/site-packages/imgui/integrations/opengl.py", line 251, in refresh_font_texture
    gl.glTexImage2D(gl.GL_TEXTURE_2D, 0, gl.GL_ALPHA, width, height, 0, gl.GL_ALPHA, gl.GL_UNSIGNED_BYTE, pixels)
  File "src/latebind.pyx", line 39, in OpenGL_accelerate.latebind.LateBind.__call__
  File "src/wrapper.pyx", line 318, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "src/wrapper.pyx", line 311, in OpenGL_accelerate.wrapper.Wrapper.__call__
  File "/usr/local/lib/python3.8/dist-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glTexImage2D,
        pyArgs = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        ),
        cArgs = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        ),
        cArguments = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        )
)
```

**Comment by KinoxKlark** [comment]
Thanks for reaching out. I confirm the issue, it is due to the usage GL flags and functions that are no longer supported in GL3.

I started to modify the integration code in order to make it compatible, but it wasn't a quick fix as I was hoping for. Fixing this `GL_ALPHA` flag works but it crashes later. Fixing another thing and it crash later. And it reveals itself to be quite a rabbit hole. 

I hope to be able to continue working on that, but I won't have time to do it rapidly. If you are in a hurry, I would advise you to rewrite a compatible backend yourself. You should be able to reuse most of `imgui/integrations/***.py`. Note that we propose some examples of backend integration, but it is not mandatory to use one of them. Pyimgui is independent of the backend, and you can write custom integration. We only give some examples. Our pygame example is only compatible with GL2, so if you need GL3 you will have to write it yourself. I would be open to PR that would propose an upgraded version if you wanted to tackle the challenge. Otherwise, I'll try to do it myself when I will have time.

**Comment by cgloeckner** [comment]
Thanks for your response!

I'm not in a hurry, but neither am I familiar enough with how imgui works under the hood. So it's probably better for me to wait for a fix in the future.

In case I find myself able to write a custom integration, I'll let you know!
