### ISSUE TITLE
Pygame + pyimgui + moderngl crashing

### ISSUE THREAD

**Issue by sudokit** [pyimgui/pyimgui#339]
Im trying to get pyimgui to work with pygame (for windowing) and moderngl (for opengl)

Code:
```python
import moderngl
from setting import *
import moderngl as mgl
import pygame as pg
import sys
import imgui

from imgui.integrations.pygame import PygameRenderer

class VoxelEngine:
    def __init__(self) -> None:
        pg.init()
        pg.display.gl_set_attribute(pg.GL_CONTEXT_MAJOR_VERSION, 4)
        pg.display.gl_set_attribute(pg.GL_CONTEXT_MINOR_VERSION, 6)
        pg.display.gl_set_attribute(pg.GL_CONTEXT_PROFILE_MASK, pg.GL_CONTEXT_PROFILE_CORE)
        pg.display.gl_set_attribute(pg.GL_DEPTH_SIZE, 24)

        pg.display.set_mode(WIN_RES.to_tuple(), flags=pg.OPENGL | pg.DOUBLEBUF)
        self.ctx = mgl.create_context()

        imgui.create_context() # type: ignore
        self.impl = PygameRenderer()

        self.io = imgui.get_io() # type: ignore
        self.io.display_size = WIN_RES

        self.ctx.enable(flags=mgl.DEPTH_TEST | mgl.CULL_FACE | mgl.BLEND) # type: ignore
        self.ctx.gc_mode = 'auto'

        self.clock = pg.time.Clock()
        self.dt = 0
        self.time = 0

        self.running = True

    def update(self) -> None:
        self.dt = self.clock.tick()
        self.time = pg.time.get_ticks() * 0.001
        pg.display.set_caption(f"{self.clock.get_fps() :.0f}")

    def render(self) -> None:
        if imgui.begin_main_menu_bar():
            if imgui.begin_menu("File", True):

                clicked_quit, selected_quit = imgui.menu_item(
                    "Quit", "Cmd+Q", False, True
                )

                if clicked_quit:
                    sys.exit(0)

                imgui.end_menu()
            imgui.end_main_menu_bar()

        is_expand, show_custom_window = imgui.begin("Custom window", True)
        if is_expand:
            imgui.text("Bars")
            imgui.text_colored("Eggs", 0.2, 1.0, 0.0)
        imgui.end()

        self.ctx.clear()
        imgui.render()
        impl.render(imgui.get_draw_data())
        pg.display.flip()

    def handle_events(self) -> None:
        for event in pg.event.get():
            if event.type == pg.QUIT or (event.type == pg.KEYDOWN and event.key == pg.K_ESCAPE):
                self.running = False
            impl.process_event(event)
        impl.process_inputs()

    def run(self) -> None:
        while self.running:
            self.handle_events()
            self.update()
            self.render()
        impl.shutdown()
        pg.quit()
        sys.exit(0)

if __name__ == '__main__':
    VoxelEngine().run()
```
(ontop of that, im not getting autocomplete when trying to complete ```imgui.*```. its also complaining that: ```"begin_main_menu_bar" is not a known member of module "imgui"```)

the error is:
```
pygame 2.5.0 (SDL 2.28.0, Python 3.11.3)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\msys64\home\user\pyvoxel\main.py", line 83, in <module>
    VoxelEngine().run()
    ^^^^^^^^^^^^^
  File "C:\msys64\home\user\pyvoxel\main.py", line 22, in __init__
    self.impl = PygameRenderer()
                ^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\imgui\integrations\pygame.py", line 14, in __init__
    super(PygameRenderer, self).__init__()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\imgui\integrations\base.py", line 18, in __init__
    self.refresh_font_texture()
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\imgui\integrations\opengl.py", line 251, in refresh_font_texture
    gl.glTexImage2D(gl.GL_TEXTURE_2D, 0, gl.GL_ALPHA, width, height, 0, gl.GL_ALPHA, gl.GL_UNSIGNED_BYTE, pixels)
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\latebind.py", line 47, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\wrapper.py", line 889, in wrapperCall
    raise err
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\wrapper.py", line 882, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1280,
        description = b'invalid enumerant',
        baseOperation = glTexImage2D,
        pyArgs = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        ),
        cArgs = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        ),
        cArguments = (
                GL_TEXTURE_2D,
                0,
                GL_ALPHA,
                512,
                64,
                0,
                GL_ALPHA,
                GL_UNSIGNED_BYTE,
                b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0...,
        )
)
```

**Comment by sudokit** [comment]
Okay i just found issue #329. This might be a duplicate .p
