### ISSUE TITLE
Can not run on WSL.

### ISSUE THREAD

**Issue by Iann1978** [pyimgui/pyimgui#342]
I run demo on wsl, but error occur.
here is error :
```
(imgui) iann@DESKTOP-EV1DSOV:~/test/imgui-demo$ python demo.py
hello imgui
version:{{version}} b'3.1 Mesa 21.2.6'
Traceback (most recent call last):
  File "/home/iann/test/imgui-demo/demo.py", line 100, in <module>
    main()
  File "/home/iann/test/imgui-demo/demo.py", line 81, in main
    impl = GlfwRenderer(window)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/imgui/integrations/glfw.py", line 12, in __init__
    super(GlfwRenderer, self).__init__()
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 60, in __init__
    super(ProgrammablePipelineRenderer, self).__init__()
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/imgui/integrations/base.py", line 17, in __init__
    self._create_device_objects()
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/imgui/integrations/opengl.py", line 108, in _create_device_objects
    self._attrib_location_tex = gl.glGetUniformLocation(self._shader_handle, "Texture")
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/iann/anaconda3/envs/imgui/lib/python3.11/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1282,
        baseOperation = glGetUniformLocation,
        cArguments = (1, b'Texture\x00'),
        result = -1
)
Segmentation fault
```
here is my code:
```

import glfw
from OpenGL.GL import *
import imgui
from imgui.integrations.glfw import GlfwRenderer

def main():
    # Initialize GLFW
    if not glfw.init():
        return

    # Create a window
    window = glfw.create_window(800, 600, "GLFW Demo", None, None)
    if not window:
        glfw.terminate()
        return


    # Make the window's context current
    glfw.make_context_current(window)
    # glfw.swap_interval(1)  # Enable vsync

    version = glGetString(GL_VERSION)
    print("version:{{version}}", version)
    

    imgui.create_context()
    impl = GlfwRenderer(window)

    # Main rendering loop
    while not glfw.window_should_close(window):
        # Clear the screen
        glClear(GL_COLOR_BUFFER_BIT)

        # Render your OpenGL code here

        # Swap front and back buffers
        glfw.swap_buffers(window)

        # Poll for and process events
        glfw.poll_events()

    # Terminate GLFW
    glfw.terminate()

if __name__ == '__main__':
    main()
```
and here is some install command:
```
conda create -n imgui python=3
conda activate imgui
pip install imgui[glfw]
```

**Comment by Aman-Anas** [comment]
Based on the stack trace it appears to be a problem running PyOpenGL's getUniformLocation function. Have you tested if a simple non-pyimgui PyOpenGL + glfw example script works? It might have to do with WSL being headless preventing glfw from working
