### ISSUE TITLE
Overflow error when using opengl, doublebuf and fullscreen

### ISSUE THREAD

**Issue by tommccallum** [pyimgui/pyimgui#374]
Hi,

I came across this overflow error when trying to do a simple change to fullscreen using pygame, opengl and the imgui integration.  The attached file reproduces it.

If you perform this line: 

```
pygame.display.set_mode((0,0), pygame.OPENGL | pygame.DOUBLEBUF | pygame.FULLSCREEN)
```
Then the pygame integration will fail with the error:

```
Traceback (most recent call last):
  File "/path/to/reproducer.py", line 61, in <module>
    impl.process_event(event)
  File "/path/to/venv/lib/python3.11/site-packages/imgui/integrations/pygame.py", line 127, in process_event
    pygame.display.set_mode(
OverflowError: signed integer is greater than maximum
```

This is produced because the surface.get_flags() function returns the value 2147483666.  The workaround is to catch this and re-enter the flags.

```
117         if event.type == pygame.VIDEORESIZE:
118             surface = pygame.display.get_surface()
119             # note: pygame does not modify existing surface upon resize,
120             #       we need to to it ourselves.

// BEGIN WORKAROUND
123             flags = surface.get_flags()
124             if flags == 2147483666:
125               flags=pygame.OPENGL | pygame.DOUBLEBUF | pygame.FULLSCREEN
// END WORKAROUND

126
127             pygame.display.set_mode(
128                 (event.w, event.h),
129                 flags=flags,
130             )
```

Packages are:
imgui==2.0.0
numpy==1.26.4
pillow==10.2.0
pygame==2.5.2
PyOpenGL==3.1.7

pygame 2.5.2 (SDL 2.28.2, Python 3.11.6)

The attachment includes both minimal reproducer and the output.

[reproducer.py.txt](https://github.com/pyimgui/pyimgui/files/14672667/reproducer.py.txt)

**Comment by learn-more** [comment]
At first glance this seems like it is a pygame issue, not specific to pyimgui?

**Comment by EaselinkBachmann** [comment]
Ran into this issue as well. `pygame.Surface.get_flags()` returns its flags as `uint32`, while `pygame.display.set_mode()` expects its flags as `int32`.

Another workaround that works without hardcoding flags is adjusting the sign of the flags manually:

```patch
diff --git a/imgui/integrations/pygame.py b/imgui/integrations/pygame.py
index bfd65b9..74f37b6 100644
--- a/imgui/integrations/pygame.py
+++ b/imgui/integrations/pygame.py
@@ -118,9 +118,12 @@ class PygameRenderer(FixedPipelineRenderer):
             surface = pygame.display.get_surface()
             # note: pygame does not modify existing surface upon resize,
             #       we need to to it ourselves.
+            flags = surface.get_flags()
+            if flags >= 2**31:
+                flags = flags - 2**32
             pygame.display.set_mode(
                 (event.w, event.h),
-                flags=surface.get_flags(),
+                flags=flags,
             )
             # existing font texure is no longer valid, so we need to refresh it
             self.refresh_font_texture()

```

I agree that this looks more like a pygame issue, but on first glance it doesn't look like pygame documents anywhere that the flags returned from `pygame.Surface.get_flags()` can be used with `pygame.display.set_mode()`, so that use case might not be officially supported.
