### ISSUE TITLE
Explosions when using wayland instead of X11 on WSL2 Ubuntu (pygame example)

### ISSUE THREAD

**Issue by nullbio** [pyimgui/pyimgui#379]
I'm using WSL2 ubuntu 24.04, and conda, here are my dependencies:

```
dependencies:
- python=3.12.4
- pyopengl==3.1.1a1
- pip
- pip:
  - pygame==2.6.0
  - imgui[full]==2.0.0
variables:
  PYGAME_DETECT_AVX2: '1'
```

When running the official pygame example [here](https://github.com/pyimgui/pyimgui/blob/master/doc/examples/integrations_pygame.py) (or other basic tests) like so:

`SDL_VIDEODRIVER=wayland python demo.py`

I get the following error:

```
~/projects/demo>:: SDL_VIDEODRIVER=wayland python demo.py
pygame 2.6.0 (SDL 2.28.4, Python 3.12.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/projects/demo/demo.py", line 65, in <module>
    main()
  File "/home/user/projects/demo/demo.py", line 59, in main
    impl.render(imgui.get_draw_data())
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/imgui/integrations/opengl.py", line 303, in render
    gl.glVertexPointer(2, gl.GL_FLOAT, imgui.VERTEX_SIZE, ctypes.c_void_p(commands.vtx_buffer_data + imgui.VERTEX_BUFFER_POS_OFFSET))
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/wrapper.py", line 806, in wrapperCall
    storeValues(
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/arrays/arrayhelpers.py", line 156, in __call__
    contextdata.setValue( self.constant, pyArgs[self.pointerIndex] )
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/contextdata.py", line 58, in setValue
    context = getContext( context )
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/tools/miniconda3/envs/demo/lib/python3.12/site-packages/OpenGL/contextdata.py", line 40, in getContext
    raise error.Error(
OpenGL.error.Error: Attempt to retrieve context when no valid context
```

If I create a demo without pyimgui that uses wayland via the env var, it works fine. For example, this works (no imgui):

```
import pygame
from pygame.locals import *
from OpenGL.GL import *
from OpenGL.GLU import *

def init_pygame():
    pygame.init()
    display = (800, 600)
    pygame.display.set_mode(display, DOUBLEBUF | OPENGL)
    pygame.display.set_caption("Pygame + OpenGL Basic Test")

def main():
    init_pygame()

    clock = pygame.time.Clock()

    while True:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                return

        # Simple OpenGL rendering to verify context
        glBegin(GL_TRIANGLES)
        glVertex3f(-0.5, -0.5, 0.0)
        glVertex3f( 0.5, -0.5, 0.0)
        glVertex3f( 0.0,  0.5, 0.0)
        glEnd()

        err = glGetError()
        if err != GL_NO_ERROR:
            print(f"OpenGL error before ImGui render: {err}")

        pygame.display.flip()
        clock.tick(60)

if __name__ == "__main__":
    main()
```

However, the official demo works if I do SDL_VIDEODRIVER=X11. So this seems to suggest there is some sort of compatibility issue with the imgui implementation?

**Comment by EaselinkBachmann** [comment]
I have the opposite issue on Sway: same crash, but only when using `SDL_VIDEODRIVER=x11`, and it's fixed with `SDL_VIDEODRIVER=wayland`.
